name = "Newb X Memories: build 2.0"
version = [0, 2, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- §lNewb x Memories §fis a brighted & beautiful shader built by §2OVENIX :)
%v
''' # %w = patch warning, %v = version
authors = ["Ovenix" , "deven"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "abe52eeb-2c15-4187-9c05-8f48198405c4" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "AROURA_SETTINGS"
materials = ["Clouds"]
description = '''
§6the most lowest§f lag (newb x legacy Aroura default settings) to reduce the lag §6for the weakest devices for NewB X Memories §b- §lRestart for the best experience!
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
Aurora Reflection Lowest Settings for NewB X Memories§f §b- §lRestart for the best experience
'''

[[subpack]]
define = "VANILLA_WATER_STYLE"
materials = ["Clouds"]
description = '''
Change §9the water to vanilla enchanced looks Settings for NewB X Memories §b- §lRestart for the best experience!
'''

[[subpack]]
define = "BLINKING_TORCH"
materials = ["RenderChunk"]
description = '''
Enable Blinking §6Torch§f Feature Settings for NewB X Memories §b- §lRestart for the best experience!
'''

[[subpack]]
define = "BRIGHT_BLUE_SKY"
materials = ["Clouds" , "LegacyCubemap" , "RenderChunk" , "Sky"]
description = '''
Change Night sky to more §3bright for NewB X Memories §b- §lRestart for the best experience!
'''

[[subpack]]
define = "CLOUDS_EXTENSION"
materials = ["Clouds"]
description = '''
Enable Multilayer Rounded Clouds (Cost lot performance)§6High Settings §ffor NewB X Memories §b- §lRestart for the best experience!
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
§lDefault
'''
