name = "Newb X Memories: build 3.0"
version = [0, 3, 0]
min_supported_mc_version = [1, 21, 20]
description = '''
§c%w
§7- §lNewb x Memories §fis a brighted & beautiful shader built by §2OVENIX :)
%v
''' # %w = patch warning, %v = version
authors = ["Ovenix" , "deven"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "abe52eeb-2c15-4187-9c05-8f48198405c4" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "LegacyCubemap", "Clouds", "EndSky", "SunMoon", "RenderChunk", "Weather", "Actor"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "RAINBOW"
materials = ["Sky"]
description = '''
Enable the §bRainbow§f for NewB X Memories §l- §bRestart for the best experience
'''

[[subpack]]
define = "SOFT_CLOUDS"
materials = ["Clouds"]
description = '''
Soft Cloud Aurora Reflection (§eLowest§f) Settings for NewB X Memories §l- §bRestart for the best experience
'''

[[subpack]]
define = "BRIGHT_BLUE_SKY"
materials = ["Clouds" , "EndSky" ,"LegacyCubemap" ,"RenderChunk" , "Sky"]
description = '''
Bright Blue Sky All Features Default (§6Medium§f) Change Night sky to more §bbright§f Extension for NewB X Memories §l- §bRestart for the best experience!
'''

[[subpack]]
define = "BLINKING_TORCH"
materials = ["RenderChunk"]
description = '''
Toggle Blinking §6Torch§f Blinking §6Torch§f Feature Settings for NewB X Memories §l- §bRestart for the best experience!
'''

[[subpack]]
define = "VANILLA_WATER_STYLE"
materials = ["RenderChunk"]
description = '''
§bVANILLA WATER STYLE §f- Change the water to vanilla enchanced looks Settings for NewB X Memories §l- §bRestart for the best experience!
'''

[[subpack]]
define = "CLOUDS_EXTENSION"
materials = ["Clouds" , "LegacyCubemap"]
description = '''
§bRounded Clouds Extension§f Subpack Summary §cEnable Multilayer Rounded Clouds§f §4(Cost lot performance)§f §6High Settings §ffor NewB X Memories §l- §bRestart for the best experience!
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
§lDefault Settings for NEWB X MEMORIES§f
'''
